// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05.04.2025, 15:26:31
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/plugins/**/*.{js,ts,mjs}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/composables/**/*.{js,ts,mjs}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/utils/**/*.{js,ts,mjs}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/pages/index.vue","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/pages/login.vue","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/pages/register.vue","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/pages/event/[id].vue","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/pages/profile/moderator.vue","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/pages/profile/organizer.vue","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/pages/profile/participant.vue","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/VAMPAD/Desktop/Новая папка (5)/event-platform/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;